<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Presentation\Grpc\Protos\Protos\**" />
	  <EmbeddedResource Remove="Presentation\Grpc\Protos\Protos\**" />
	  <None Remove="Presentation\Grpc\Protos\Protos\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.3.1" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
		<PackageReference Include="Grpc.Tools" Version="2.76.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Google.Protobuf" Version="3.33.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\RiraBackEndTask.SharedKernel\RiraBackEndTask.SharedKernel.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Protobuf Include="Presentation\Grpc\Protos\person.proto" GrpcServices="Server" CompileOutputs="true" />
	</ItemGroup>


</Project>
